namespace FMOD
{
    public enum DSP_PARAMETER_DATA_TYPE
    {
        DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES_MULTI = -5, // 0xFFFFFFFB
        DSP_PARAMETER_DATA_TYPE_FFT = -4, // 0xFFFFFFFC
        DSP_PARAMETER_DATA_TYPE_SIDECHAIN = -3, // 0xFFFFFFFD
        DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES = -2, // 0xFFFFFFFE
        DSP_PARAMETER_DATA_TYPE_OVERALLGAIN = -1, // 0xFFFFFFFF
        DSP_PARAMETER_DATA_TYPE_USER = 0,
    }
}
